# Generated by Django 5.0.6 on 2024-06-21 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userlogincount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_status',
            field=models.CharField(choices=[('both', 'Both Parents'), ('single', 'Single Parent'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(default='Unknown Region', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default='REG000', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(default='First Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(default='Last Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
