# Generated by Django 5.0.6 on 2024-07-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_student_course_alter_student_dob_and_more'),
    ]

    operations = [
    ]
