# Generated by Django 5.0.6 on 2024-07-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_fix_null_user_ids'),
    ]

    operations = [
    ]
