# Generated by Django 5.0.6 on 2024-07-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20240701_1151'),
    ]

    operations = [
    ]
