# Generated by Django 5.0.6 on 2024-07-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20240701_1152'),
    ]

    operations = [
    ]
