# Generated by Django 5.0.6 on 2024-07-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_student_user'),
    ]

    operations = [
    ]
