# Generated by Django 5.0.6 on 2024-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
