# Generated by Django 5.0.6 on 2024-07-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_student_user'),
        ('events', '0021_add_default_user_to_students'),
    ]

    operations = [
    ]
